name: Feature Request
description: Suggest an idea for this project
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your suggestion! Please fill in the details below.
  - type: input
    id: feature
    attributes:
      label: Feature
      description: Briefly describe the new feature you want
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this feature useful?
